### ISSUE TITLE
Authentication missing from the OpenAPI specs

### ISSUE THREAD

**Issue by ping-localhost** [trisacrypto/envoy#108]
I've generated an OpenAPI client using the provided OpenAPI spec, but it seems that the (re)authenticate have not yet been added to the spec.

**Comment by bbengfort** [comment]
@ping-localhost unfortunately we haven't managed to get auto-generated swagger docs going yet so we'll have to manually update them with the new endpoints. We'll have revisions up by the end of the week!

**Comment by ping-localhost** [comment]
If I have some time later today/this week, I can also try and update the definition.

**Comment by bbengfort** [comment]
We would really appreciate that!
