### ISSUE TITLE
RPC API method for sending Travel Rule transaction (secure envelope)

### ISSUE THREAD

**Issue by olegyakovlev** [trisacrypto/envoy#129]
Hi Developers,
There are many RPC API methods but I could not find any method for sending Travel Rule transaction (secure envelope).
This functionality is available via web interface but it will be very handy to have related API method.

**Comment by daniellemaxwell** [comment]
Hi @olegyakovlev. Thank you for reaching out. There is a [`SendPreparedTransaction`](https://github.com/trisacrypto/envoy/blob/37287c00cc47fdb17678548a9057f711d2e5bafc/pkg/web/routes.go#L159) that may be used to send a secure envelope. 

Although primarily created for the UI, it may be used via the API as well. There's also the option to use the [`SendEnvelopeForTransaction`](https://github.com/trisacrypto/envoy/blob/37287c00cc47fdb17678548a9057f711d2e5bafc/pkg/web/routes.go#L165) method.

If you have any additional questions, let me know.

**Comment by ping-localhost** [comment]
@daniellemaxwell We could properly expose this via the OpenAPI spec, which I've done in https://github.com/ping-localhost/envoy/pull/1. I'll prepare another MR once https://github.com/trisacrypto/envoy/pull/131 has been merged.

**Comment by daniellemaxwell** [comment]
@ping-localhost Thank you!
