### ISSUE TITLE
Time shown in table is "incorrect"

### ISSUE THREAD

**Issue by ping-localhost** [trisacrypto/envoy#130]
Just created this secure envelope (can confirm that local development now works, thank you). The time stored in the DB is, I'm guessing, UTC, but it also displayed in the interface as such, which is confusing.

![image](https://github.com/trisacrypto/envoy/assets/37925797/62e0d901-e8c9-47c2-a1a4-f15ed648a4b2)

**Comment by daniellemaxwell** [comment]
Hi @ping-localhost. Thank you for reaching out to us about this. Yes, the timestamp for `Last Update` is stored in UTC and not the local time. I completely understand the confusion. We recently created a ticket to address the bug so that it may be resolved soon.
